### ISSUE TITLE
DateTime parse error while querying word of the day

### ISSUE THREAD

**Issue by Suyash458** [wordnik/wordnik-python3#4]
Trace
```
>>> wordoftheday_api.getWordOfTheDay()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\Software\Python36\lib\site-packages\wordnik\WordsApi.py", line 141, in getWordOfTheDay
    responseObject = self.apiClient.deserialize(response, 'WordOfTheDay')
  File "E:\Software\Python36\lib\site-packages\wordnik\swagger.py", line 165, in deserialize
    "%Y-%m-%dT%H:%M:%S.%f"))
  File "E:\Software\Python36\lib\_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "E:\Software\Python36\lib\_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2019-04-27T03:00:00' does not match format '%Y-%m-%dT%H:%M:%S.%f'
``` 
Changing line 175 in `swagger.py` to `setattr(instance, attr, datetime.datetime.strptime(value[:-5], "%Y-%m-%dT%H:%M:%S"))` seems to fix it. The same [issue](https://github.com/wordnik/wordnik-python/issues/29) exists with the library for python 2.7 as well

**Comment by tortured1** [comment]
I am also having this same issue.  I was able to work around it by making the following small change in swagger.py:

Line 170:
 ```
                   #                          "%Y-%m-%dT%H:%M:%S.%f"))
                                               "%Y-%m-%dT%H:%M:%S"))
```
